substitutions:
  tx_pin: GPIO17
  rx_pin: GPIO16

esphome:
  name: "mbus-meter"

# esp8266:
#   board: d1_mini

esp32:
  board: esp32doit-devkit-v1

wifi:
  domain: ""
  networks:
    - ssid: "MAS_KG"
      password: "5747541010852453"

api:
  encryption:
    key: "tBrCD12THOrfDuVOS7egI8eJmJJGJChgV7ysqoBsFug="

# Enable logging
logger:
  tx_buffer_size: 1024
  level: DEBUG
  # level: VERBOSE
  # level: VERY_VERBOSE

# api: !include _api.yaml
# ota: !include _ota.yaml
# wifi: !include _wifi.yaml

uart:
  baud_rate: 2400
  data_bits: 8
  id: m_bus
  parity: EVEN
  rx_pin: ${rx_pin}
  stop_bits: 1
  tx_pin: ${tx_pin}

mbus:
  secondary_address: 0x0025426642042002
  interval: "5s"
# ---------------------------------------------------------------------------------------
# debug component
# debug:
#   update_interval: 5s

# text_sensor:
#   - platform: debug
#     reset_reason:
#       name: "Reset Reason"

sensor:
  # - platform: debug
  #   free:
  #     name: "Heap Free"
  #   block:
  #     name: "Heap Max Block"
  # loop_time:
  #   name: "Loop Time"
  # ---------------------------------------------------------------------------------------
  - platform: mbus_sensor
    data_index: 0
    factor: 10
    name: "Strom-OG-Verbrauch"
    accuracy_decimals: 1
    device_class: power
    icon: "mdi:flash"
    state_class: measurement
    unit_of_measurement: "Wh"
