substitutions:
  tx_pin: GPIO17
  rx_pin: GPIO16

esphome:
  name: "mbus-meter"

# esp8266:
#   board: d1_mini

esp32:
  board: esp32doit-devkit-v1

# Enable logging
logger:
  tx_buffer_size: 1024
  level: VERBOSE
  # level: VERY_VERBOSE

# api: !include _api.yaml
# ota: !include _ota.yaml
# wifi: !include _wifi.yaml

uart:
  baud_rate: 2400
  data_bits: 8
  id: m_bus
  parity: EVEN
  rx_pin: ${rx_pin}
  stop_bits: 1
  tx_pin: ${tx_pin}

mbus:
  # secondary_address: 0x0025426642042002
